name: dokter_dirumah
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  provider: ^6.0.5
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  uuid: ^3.0.7
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
