// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLh-oMSOI_OHxNSVlqmbRKoOWGsHTC-FM',
    appId: '1:1010107276606:web:a8d8f3477eb8047b8d206f',
    messagingSenderId: '1010107276606',
    projectId: 'dokterdirumah-43173',
    authDomain: 'dokterdirumah-43173.firebaseapp.com',
    storageBucket: 'dokterdirumah-43173.appspot.com',
    measurementId: 'G-SP9B2X3H64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ7OviPFN6ox_cNtfvDCUieYB1BcdIgsw',
    appId: '1:1010107276606:android:f2f972c98afc39ec8d206f',
    messagingSenderId: '1010107276606',
    projectId: 'dokterdirumah-43173',
    storageBucket: 'dokterdirumah-43173.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTv6gjzCZEeC1mPSA0k3boRpSmYDKvSB8',
    appId: '1:1010107276606:ios:61ab1825f3c168008d206f',
    messagingSenderId: '1010107276606',
    projectId: 'dokterdirumah-43173',
    storageBucket: 'dokterdirumah-43173.appspot.com',
    iosClientId: '1010107276606-gk0me6nggq0a4goqn6267v0jmglgb0fp.apps.googleusercontent.com',
    iosBundleId: 'com.example.dokterDirumah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTv6gjzCZEeC1mPSA0k3boRpSmYDKvSB8',
    appId: '1:1010107276606:ios:61ab1825f3c168008d206f',
    messagingSenderId: '1010107276606',
    projectId: 'dokterdirumah-43173',
    storageBucket: 'dokterdirumah-43173.appspot.com',
    iosClientId: '1010107276606-gk0me6nggq0a4goqn6267v0jmglgb0fp.apps.googleusercontent.com',
    iosBundleId: 'com.example.dokterDirumah',
  );
}
